import Head from 'next/head';
import Container from '@/components/Container';
import TableWrapper from '@/components/Table/TableWrapper';
import axios from 'axios';

export default function Home({ data }) {
  // console.log(data);
  return (
    <>
      <Head>
        <title>Delevery Note</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Container>
          <TableWrapper data={data} />
        </Container>
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  const res = await axios.get('http://localhost:3001/deliverydata');

  return {
    props: {
      data: res.data,
    },
  };
};
